# Generated by Django 5.2.7 on 2025-10-08 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название плейлиста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='обложка')),
                ('is_public', models.BooleanField(default=True, verbose_name='публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя артиста')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='биография')),
                ('verified', models.BooleanField(default=False, verbose_name='верифицирован')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='фото')),
                ('total_listens', models.IntegerField(default=0, verbose_name='всего прослушиваний')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='d_artist_name_52962c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название альбома')),
                ('release_date', models.DateField(verbose_name='дата выпуска')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='обложка')),
                ('album_type', models.CharField(choices=[('album', 'Альбом'), ('ep', 'EP'), ('single', 'Сингл')], max_length=10, verbose_name='тип альбома')),
                ('genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='жанр')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.artist', verbose_name='артист')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название трека')),
                ('duration', models.IntegerField(verbose_name='длительность (секунды)')),
                ('listens_count', models.IntegerField(default=0, verbose_name='количество прослушиваний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d.album', verbose_name='альбом')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='d.artist', verbose_name='участвующие артисты')),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.artist', verbose_name='основной артист')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['album'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='позиция в плейлисте')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.track')),
            ],
            options={
                'verbose_name': 'Трек в плейлисте',
                'verbose_name_plural': 'Треки в плейлистах',
                'ordering': ['playlist', 'position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='d.PlaylistTrack', to='d.track', verbose_name='треки'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='хэш пароля')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='аватар')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('subscription_type', models.CharField(choices=[('free', 'Бесплатная'), ('premium', 'Премиум')], default='free', max_length=10, verbose_name='тип подписки')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
                'indexes': [models.Index(fields=['username'], name='d_user_usernam_442fcf_idx'), models.Index(fields=['email'], name='d_user_email_a8a36f_idx')],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d.user', verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True, verbose_name='время прослушивания')),
                ('playback_duration', models.IntegerField(verbose_name='длительность прослушивания')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.track', verbose_name='трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'История прослушиваний',
                'verbose_name_plural': 'История прослушиваний',
                'ordering': ['-listened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d.artist', verbose_name='артист')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d.track', verbose_name='трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['user'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='d_album_artist__0da128_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['main_artist', 'listens_count'], name='d_track_main_ar_826cab_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album'], name='d_track_album_i_57acd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', 'listened_at'], name='d_listening_user_id_31c5c3_idx'),
        ),
    ]
