# Generated by Django 5.2.8 on 2025-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
