# Generated by Django 5.2.8 on 2025-11-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0002_track_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='cover_url',
        ),
    ]
