# Generated by Django 5.2.7 on 2025-10-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0002_remove_user_subscription_type_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='listened_at',
            field=models.DateField(auto_now_add=True, verbose_name='время прослушивания'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='added_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='имя пользователя'),
        ),
    ]
