# Generated by Django 5.2.8 on 2025-11-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0003_remove_track_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата добавления'),
        ),
    ]
