# Generated by Django 5.2.8 on 2025-11-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0004_track_cover_url_alter_track_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(verbose_name='длительность'),
        ),
    ]
