# Generated by Django 5.2.8 on 2025-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0007_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(verbose_name='длительность'),
        ),
    ]
