# Generated by Django 5.2.6 on 2025-09-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('birthday', models.CharField(verbose_name='Дата рождения')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Навзание')),
                ('id_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.publisher')),
            ],
        ),
    ]
